const API_URL_ROOT = process.env.REACT_APP_WEBSITEROOT + "/api";
const WEBSITE_ROOT = process.env.REACT_APP_WEBSITEROOT;
const MAX_ITEM_TABLE_DISPLAY_SIZE = 30;
export {API_URL_ROOT, WEBSITE_ROOT, MAX_ITEM_TABLE_DISPLAY_SIZE}